### ISSUE TITLE
Just tried AMYCNE, stack trace after a while

### ISSUE THREAD

**Issue by bwlang** [J35P312/AMYCNE#1]
I get this stack output:

I mapped data to grch38 (the full set, including alt contigs etc.)
I used sambamba depth to generate the coverage file and your GC script for the GC tsv file.

example input:
```
$head ref_gc.tsv 
1       0       100     -1.0
1       100     200     -1.0
1       200     300     -1.0
1       300     400     -1.0
1       400     500     -1.0
1       500     600     -1.0
1       600     700     -1.0
1       700     800     -1.0
1       800     900     -1.0
1       900     1000    -1.0
$ tail ref_gc.tsv 
HLA-DRB1*16:02:01       10100   10200   0.4
HLA-DRB1*16:02:01       10200   10300   0.4
HLA-DRB1*16:02:01       10300   10400   0.52
HLA-DRB1*16:02:01       10400   10500   0.53
HLA-DRB1*16:02:01       10500   10600   0.38
HLA-DRB1*16:02:01       10600   10700   0.52
HLA-DRB1*16:02:01       10700   10800   0.45
HLA-DRB1*16:02:01       10800   10900   0.49
HLA-DRB1*16:02:01       10900   11000   0.55
HLA-DRB1*16:02:01       11000   11005   0.2

$ head Y2_6pg_13_cycles.md.even_cov.cov 
# chrom    chromStart      chromEnd        readCount       meanCoverage    sampleName
1       16400   16500   1       0.7     Y2_6pg_13_cycles
1       16500   16600   2       0.63    Y2_6pg_13_cycles
1       16600   16700   1       0.17    Y2_6pg_13_cycles
1       16700   16800   0       0       Y2_6pg_13_cycles
1       16800   16900   0       0       Y2_6pg_13_cycles
1       16900   17000   0       0       Y2_6pg_13_cycles
1       17000   17100   0       0       Y2_6pg_13_cycles
1       17100   17200   0       0       Y2_6pg_13_cycles
1       17200   17300   0       0       Y2_6pg_13_cycles
$ tail Y2_6pg_13_cycles.md.even_cov.cov 
HLA-DRB1*16:02:01       10000   10100   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10100   10200   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10200   10300   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10300   10400   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10400   10500   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10500   10600   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10600   10700   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10700   10800   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10800   10900   0       0       Y2_6pg_13_cycles
HLA-DRB1*16:02:01       10900   11000   0       0       Y2_6pg_13_cycles
```

```
Command output:
  finished reading the coverage data
  applying filters
  computing coverage histogram

Command error:
  /mnt/flash_scratch/nextflow_conda/env-4731703d9d1e13495b9cb3da6a63e29e/lib/python2.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  /mnt/flash_scratch/nextflow_conda/env-4731703d9d1e13495b9cb3da6a63e29e/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
    ret = ret.dtype.type(ret / rcount)
  Traceback (most recent call last):
    File "...bin/AMYCNE.py", line 164, in <module>
      call.main(Data,GC_hist,args)
    File "call.py", line 338, in call.main
      ratio_hist=chromosome_hist(Data,args.Q)
    File "call.py", line 156, in call.chromosome_hist
      for chromosome in Data["chromosomes"]:
  TypeError: list indices must be integers, not str
```

**Comment by J35P312** [comment]
Hello there!
the AMYCNE call module is a bit shaky, I'm developing it mostly as a side project, so proceed with caution!

The GC file looks fine. The coverage file might need some fixing:

I would start by removing the meanCoverage, and sampleName column. 

The accepted columns (tab separated) are:

chromosome,start,end,coverage

or

chromosome,start,end,coverage,per_bin_quality_score

AMYCNE call is only tested on 30X human whole genomes. If the coverage is low, you may need to change the --s_cutoff limit.

Mostly, I'm still using CNVnator - I found these tools to perform similarily on 30X data. Feel free to give AMYCNE call a try, otherwise, I would reccomend you to try CNVnator!

Good luck!
