### ISSUE TITLE
UnboundLocalError: local variable 'region' referenced before assignment

### ISSUE THREAD

**Issue by zkstewart** [J35P312/AMYCNE#6]
Trying to use the program returns the error in the title. The cause appears to be in `genotype.py` at line 40:

```
def main(Data,GC_hist,args):
    #get the coverage across the region

    coverage_list=[]
    len_list=[]
    gc_list=[]
    ref_list=[]
    total_bin_list=[]
    bin_count = 0
    used_bin_count = 0
    
    operations=[]
    if args.region:
        for line in open(args.region):
            mode,regions = retrieve_regions(line)
            operations.append({"mode": mode, "regions":regions,"command":line.strip()})
    else:
    
        chromosome=region.split(":")[0]
```

The `chromosome=region.split(":")[0]` line fails because it calls `region` (which has not been defined yet) rather than `args.region` as it's likely meant to.

Edit: It should be `args.R` not `args.region`.

**Comment by zkstewart** [comment]
Line 44 also needs a fix. Instead of:

`operations.append({"mode": "sum", "regions":[chromosome]+pos,"command":args.R})`

It should be:

`operations.append({"mode": "sum", "regions":[[chromosome]+pos],"command":args.R})`

Since line 52 begins iterating over the `operation["regions"]` values expecting a list of lists. With the current code, I end up receiving an error like:

```
Traceback (most recent call last):
  File "/home/stewarz2/various_programs/AMYCNE/AMYCNE.py", line 118, in <module>
    genotype.main(Data,GC_hist,args)
  File "/mnt/hpccs01/home/stewarz2/various_programs/AMYCNE/genotype.py", line 53, in main
    cn, gc, length,ref,bins,used_bins,bin_list =common.regional_cn_est( Data ,GC_hist, region,args.Q )
  File "/mnt/hpccs01/home/stewarz2/various_programs/AMYCNE/common.py", line 100, in regional_cn_est
    start=int(region[1])
ValueError: invalid literal for int() with base 10: 'C'
```

Since the second letter in my contig identifier is "C".

**Comment by zkstewart** [comment]
The code in `genotype.py` also doesn't handle the edge case (which occurs in my data) where a gene region obtains either 0 read counts, or has 0 quality from tiddit. When it goes on to perform calculations including:

`regional_coverage=sum(scaled_cov)/float(sum(len_list))`

It receives a `ZeroDivisionError: float division by zero` error since `sum(scaled_cov)` and `sum(len_list)` are both 0.

To make AMYCNE run for me, I've edited the code like:

```
if mode == "sum":
    for i in range(0,len(total_bin_list)):
        total_bin_list[i]=total_bin_list[i]*args.plody*nregions
elif mode == "avg":
    for i in range(0,len(total_bin_list)):
        total_bin_list[i]=total_bin_list[i]*args.plody
SEM=(numpy.std(total_bin_list)/numpy.sqrt(used_bin_count))

scaled_cov=[]
scaled_gc=[]
scaled_ref=[]

try:
    regional_coverage=sum(scaled_cov)/float(sum(len_list))
    regional_gc=sum(scaled_gc)/float(sum(len_list))
    reference_coverage=sum(scaled_ref)/float(sum(len_list))
    ci="({},{})".format(round(regional_coverage-SEM*1.96,2),round(regional_coverage+SEM*1.96,2))
except:
    regional_coverage=0
    regional_gc=0
    reference_coverage=0
    ci="(0,0)"
```

I moved the code where `SEM` is calculated above the `try: except` clause to accommodate the changes. Since I'm running AMYCNE per gene, I think this solution will not propagate any weird behaviour downstream for myself, but I'm not sure what would happen if processing multiple regions. Putting everything as 0 seems to make sense to me since I would interpret this scenario as occurring when the genomic region has been deleted in the sequenced organism relative to the reference, hence a copy number of 0 is appropriate.

Nonetheless, if the author is still maintaining this code, it could be nice to implement these changes with their knowledge of the codebase. Or I could propose a pull request if they approve and my indicated thinking is correct.

**Comment by J35P312** [comment]
Hello!
And thanks for trying AMYCNE! Feel free to send a pull request, and I will have a look at it.
However, as you notice AMYCNE is a bit rough and is currently not being developed, you may find a more up to date software elsewhere.

Good luck!
//Jesper
